name: studydocs
description: "This is an application that allows users to post as well as a library for learning materials."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # THEME & UI
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  dotted_border: ^2.1.0
  font_awesome_flutter: ^10.7.0

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  equatable: ^2.0.5

  # UTILS
  intl: ^0.19.0
  logger: ^2.4.0
  dartz: ^0.10.1
  intl_phone_field: ^3.2.0

  # FONT & ASSETS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/notifications/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
